const developers = [
  {
    rank: 1,
    username: "twpayne",
    name: "Tom Payne",
    url: "https://github.com/twpayne",
    avatar: "https://avatars.githubusercontent.com/u/6942?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "chezmoi",
      description: null,
      url: "https://github.com/twpayne/chezmoi",
    },
  },
  {
    rank: 2,
    username: "mfussenegger",
    name: "Mathias Fußenegger",
    url: "https://github.com/mfussenegger",
    avatar: "https://avatars.githubusercontent.com/u/38700?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "nvim-dap",
      description: null,
      url: "https://github.com/mfussenegger/nvim-dap",
    },
  },
  {
    rank: 3,
    username: "leoluk",
    name: "Leopold Schabel",
    url: "https://github.com/leoluk",
    avatar: "https://avatars.githubusercontent.com/u/859697?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "slack-workspace-sidebar",
      description: null,
      url: "https://github.com/leoluk/slack-workspace-sidebar",
    },
  },
  {
    rank: 4,
    username: "FayasNoushad",
    name: "Fayas Noushad",
    url: "https://github.com/FayasNoushad",
    avatar: "https://avatars.githubusercontent.com/u/76828314?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "Stylish-Text",
      description: null,
      url: "https://github.com/FayasNoushad/Stylish-Text",
    },
  },
  {
    rank: 5,
    username: "derailed",
    name: "Fernand Galiana",
    url: "https://github.com/derailed",
    avatar: "https://avatars.githubusercontent.com/u/4060?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "k9s",
      description: null,
      url: "https://github.com/derailed/k9s",
    },
  },
  {
    rank: 6,
    username: "noot",
    name: "noot",
    url: "https://github.com/noot",
    avatar: "https://avatars.githubusercontent.com/u/36753753?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "atomic-swap",
      description: null,
      url: "https://github.com/noot/atomic-swap",
    },
  },
  {
    rank: 7,
    username: "kripken",
    name: "Alon Zakai",
    url: "https://github.com/kripken",
    avatar: "https://avatars.githubusercontent.com/u/173661?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "ammo.js",
      description: null,
      url: "https://github.com/kripken/ammo.js",
    },
  },
  {
    rank: 8,
    username: "felangel",
    name: "Felix Angelov",
    url: "https://github.com/felangel",
    avatar: "https://avatars.githubusercontent.com/u/8855632?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "bloc",
      description: null,
      url: "https://github.com/felangel/bloc",
    },
  },
  {
    rank: 9,
    username: "asvetlov",
    name: "Andrew Svetlov",
    url: "https://github.com/asvetlov",
    avatar: "https://avatars.githubusercontent.com/u/356399?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: null,
      description: null,
      url: null,
    },
  },
  {
    rank: 10,
    username: "lukeed",
    name: "Luke Edwards",
    url: "https://github.com/lukeed",
    avatar: "https://avatars.githubusercontent.com/u/5855893?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "worktop",
      description: null,
      url: "https://github.com/lukeed/worktop",
    },
  },
  {
    rank: 11,
    username: "sbc100",
    name: "Sam Clegg",
    url: "https://github.com/sbc100",
    avatar: "https://avatars.githubusercontent.com/u/515813?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: null,
      description: null,
      url: null,
    },
  },
  {
    rank: 12,
    username: "fcakyon",
    name: "fatih",
    url: "https://github.com/fcakyon",
    avatar: "https://avatars.githubusercontent.com/u/34196005?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "craft-text-detector",
      description: null,
      url: "https://github.com/fcakyon/craft-text-detector",
    },
  },
  {
    rank: 13,
    username: "ThePrimeagen",
    name: "ThePrimeagen",
    url: "https://github.com/ThePrimeagen",
    avatar: "https://avatars.githubusercontent.com/u/4458174?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "harpoon",
      description: null,
      url: "https://github.com/ThePrimeagen/harpoon",
    },
  },
  {
    rank: 14,
    username: "rmosolgo",
    name: "Robert Mosolgo",
    url: "https://github.com/rmosolgo",
    avatar: "https://avatars.githubusercontent.com/u/2231765?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "graphql-ruby",
      description: null,
      url: "https://github.com/rmosolgo/graphql-ruby",
    },
  },
  {
    rank: 15,
    username: "PySimpleGUI",
    name: "PySimpleGUI",
    url: "https://github.com/PySimpleGUI",
    avatar: "https://avatars.githubusercontent.com/u/46163555?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "PySimpleGUI",
      description: null,
      url: "https://github.com/PySimpleGUI/PySimpleGUI",
    },
  },
  {
    rank: 16,
    username: "miekg",
    name: "Miek Gieben",
    url: "https://github.com/miekg",
    avatar: "https://avatars.githubusercontent.com/u/353371?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "dns",
      description: null,
      url: "https://github.com/miekg/dns",
    },
  },
  {
    rank: 17,
    username: "PatrickAlphaC",
    name: "Patrick Collins",
    url: "https://github.com/PatrickAlphaC",
    avatar: "https://avatars.githubusercontent.com/u/54278053?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "dungeons-and-dragons-nft",
      description: null,
      url: "https://github.com/PatrickAlphaC/dungeons-and-dragons-nft",
    },
  },
  {
    rank: 18,
    username: "raysan5",
    name: "Ray",
    url: "https://github.com/raysan5",
    avatar: "https://avatars.githubusercontent.com/u/5766837?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "raylib",
      description: null,
      url: "https://github.com/raysan5/raylib",
    },
  },
  {
    rank: 19,
    username: "ericmjl",
    name: "Eric Ma",
    url: "https://github.com/ericmjl",
    avatar: "https://avatars.githubusercontent.com/u/2631566?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "nxviz",
      description: null,
      url: "https://github.com/ericmjl/nxviz",
    },
  },
  {
    rank: 20,
    username: "snipe",
    name: "snipe",
    url: "https://github.com/snipe",
    avatar: "https://avatars.githubusercontent.com/u/197404?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "snipe-it",
      description: null,
      url: "https://github.com/snipe/snipe-it",
    },
  },
  {
    rank: 21,
    username: "kyazdani42",
    name: "Kiyan",
    url: "https://github.com/kyazdani42",
    avatar: "https://avatars.githubusercontent.com/u/23156099?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "nvim-tree.lua",
      description: null,
      url: "https://github.com/kyazdani42/nvim-tree.lua",
    },
  },
  {
    rank: 22,
    username: "jorgecarleitao",
    name: "Jorge Leitao",
    url: "https://github.com/jorgecarleitao",
    avatar: "https://avatars.githubusercontent.com/u/2772607?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "arrow2",
      description: null,
      url: "https://github.com/jorgecarleitao/arrow2",
    },
  },
  {
    rank: 23,
    username: "daohu527",
    name: "zero",
    url: "https://github.com/daohu527",
    avatar: "https://avatars.githubusercontent.com/u/10419854?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "dig-into-apollo",
      description: null,
      url: "https://github.com/daohu527/dig-into-apollo",
    },
  },
  {
    rank: 24,
    username: "sebavan",
    name: "sebavan",
    url: "https://github.com/sebavan",
    avatar: "https://avatars.githubusercontent.com/u/16655165?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: null,
      description: null,
      url: null,
    },
  },
  {
    rank: 25,
    username: "guybedford",
    name: "Guy Bedford",
    url: "https://github.com/guybedford",
    avatar: "https://avatars.githubusercontent.com/u/598730?s=96&v=4",
    since: "daily",
    popularRepository: {
      repositoryName: "es-module-lexer",
      description: null,
      url: "https://github.com/guybedford/es-module-lexer",
    },
  },
];

export default developers;
