const repositories = [
  {
    rank: 1,
    username: "Panshak",
    repositoryName: "arcinvoice",
    url: "https://github.com/Panshak/arcinvoice",
    description:
      "Fullstack open source Invoicing application made with MongoDB, Express, React & Nodejs (MERN)",
    language: "JavaScript",
    languageColor: "#f1e05a",
    totalStars: 455,
    forks: 81,
    starsSince: 119,
    since: "daily",
    builtBy: [
      {
        username: "Panshak",
        url: "https://github.com/Panshak",
        avatar: "https://avatars.githubusercontent.com/u/15835693?s=40&v=4",
      },
    ],
  },
  {
    rank: 2,
    username: "dreamhead",
    repositoryName: "patterns-of-distributed-systems",
    url: "https://github.com/dreamhead/patterns-of-distributed-systems",
    description: "《Patterns of Distributed Systems》中文版",
    language: null,
    languageColor: null,
    totalStars: 994,
    forks: 107,
    starsSince: 146,
    since: "daily",
    builtBy: [
      {
        username: "dreamhead",
        url: "https://github.com/dreamhead",
        avatar: "https://avatars.githubusercontent.com/u/26388?s=40&v=4",
      },
      {
        username: "ynfeng",
        url: "https://github.com/ynfeng",
        avatar: "https://avatars.githubusercontent.com/u/7802558?s=40&v=4",
      },
      {
        username: "liul85",
        url: "https://github.com/liul85",
        avatar: "https://avatars.githubusercontent.com/u/1312723?s=40&v=4",
      },
      {
        username: "shshao-tw",
        url: "https://github.com/shshao-tw",
        avatar: "https://avatars.githubusercontent.com/u/81790965?s=40&v=4",
      },
    ],
  },
  {
    rank: 3,
    username: "hoppscotch",
    repositoryName: "hoppscotch",
    url: "https://github.com/hoppscotch/hoppscotch",
    description: "👽Open source API development ecosystemhttps://hoppscotch.io",
    language: "Vue",
    languageColor: "#41b883",
    totalStars: 33619,
    forks: 2326,
    starsSince: 54,
    since: "daily",
    builtBy: [
      {
        username: "liyasthomas",
        url: "https://github.com/liyasthomas",
        avatar: "https://avatars.githubusercontent.com/u/10395817?s=40&v=4",
      },
      {
        username: "AndrewBastin",
        url: "https://github.com/AndrewBastin",
        avatar: "https://avatars.githubusercontent.com/u/9131943?s=40&v=4",
      },
      {
        username: "apps/dependabot-preview",
        url: "https://github.com/apps/dependabot-preview",
        avatar: "https://avatars.githubusercontent.com/in/2141?s=40&v=4",
      },
      {
        username: "jamesgeorge007",
        url: "https://github.com/jamesgeorge007",
        avatar: "https://avatars.githubusercontent.com/u/25279263?s=40&v=4",
      },
      {
        username: "dmitryyankowski",
        url: "https://github.com/dmitryyankowski",
        avatar: "https://avatars.githubusercontent.com/u/20114263?s=40&v=4",
      },
    ],
  },
  {
    rank: 4,
    username: "Chia-Network",
    repositoryName: "chia-blockchain",
    url: "https://github.com/Chia-Network/chia-blockchain",
    description:
      "Chia blockchain python implementation (full node, farmer, harvester, timelord, and wallet)",
    language: "Python",
    languageColor: "#3572A5",
    totalStars: 9535,
    forks: 1699,
    starsSince: 10,
    since: "daily",
    builtBy: [
      {
        username: "Yostra",
        url: "https://github.com/Yostra",
        avatar: "https://avatars.githubusercontent.com/u/7254853?s=40&v=4",
      },
      {
        username: "mariano54",
        url: "https://github.com/mariano54",
        avatar: "https://avatars.githubusercontent.com/u/3069354?s=40&v=4",
      },
      {
        username: "hoffmang9",
        url: "https://github.com/hoffmang9",
        avatar: "https://avatars.githubusercontent.com/u/30377676?s=40&v=4",
      },
      {
        username: "richardkiss",
        url: "https://github.com/richardkiss",
        avatar: "https://avatars.githubusercontent.com/u/5336?s=40&v=4",
      },
      {
        username: "almogdepaz",
        url: "https://github.com/almogdepaz",
        avatar: "https://avatars.githubusercontent.com/u/25171429?s=40&v=4",
      },
    ],
  },
  {
    rank: 5,
    username: "microsoft",
    repositoryName: "ML-For-Beginners",
    url: "https://github.com/microsoft/ML-For-Beginners",
    description:
      "12 weeks, 26 lessons, 52 quizzes, classic Machine Learning for all",
    language: "Jupyter Notebook",
    languageColor: "#DA5B0B",
    totalStars: 25704,
    forks: 5303,
    starsSince: 36,
    since: "daily",
    builtBy: [
      {
        username: "jlooper",
        url: "https://github.com/jlooper",
        avatar: "https://avatars.githubusercontent.com/u/1450004?s=40&v=4",
      },
      {
        username: "softchris",
        url: "https://github.com/softchris",
        avatar: "https://avatars.githubusercontent.com/u/4598064?s=40&v=4",
      },
      {
        username: "minwook-shin",
        url: "https://github.com/minwook-shin",
        avatar: "https://avatars.githubusercontent.com/u/12551635?s=40&v=4",
      },
      {
        username: "davidit33",
        url: "https://github.com/davidit33",
        avatar: "https://avatars.githubusercontent.com/u/63550116?s=40&v=4",
      },
      {
        username: "feiyun0112",
        url: "https://github.com/feiyun0112",
        avatar: "https://avatars.githubusercontent.com/u/10190938?s=40&v=4",
      },
    ],
  },
  {
    rank: 6,
    username: "microsoft",
    repositoryName: "Web-Dev-For-Beginners",
    url: "https://github.com/microsoft/Web-Dev-For-Beginners",
    description: "24 Lessons, 12 Weeks, Get Started as a Web Developer",
    language: "JavaScript",
    languageColor: "#f1e05a",
    totalStars: 36779,
    forks: 5238,
    starsSince: 64,
    since: "daily",
    builtBy: [
      {
        username: "jlooper",
        url: "https://github.com/jlooper",
        avatar: "https://avatars.githubusercontent.com/u/1450004?s=40&v=4",
      },
      {
        username: "San1ay",
        url: "https://github.com/San1ay",
        avatar: "https://avatars.githubusercontent.com/u/54913971?s=40&v=4",
      },
      {
        username: "ManuSquall",
        url: "https://github.com/ManuSquall",
        avatar: "https://avatars.githubusercontent.com/u/29026887?s=40&v=4",
      },
      {
        username: "silverskyvicto",
        url: "https://github.com/silverskyvicto",
        avatar: "https://avatars.githubusercontent.com/u/3609003?s=40&v=4",
      },
      {
        username: "EugeneGohh",
        url: "https://github.com/EugeneGohh",
        avatar: "https://avatars.githubusercontent.com/u/64187129?s=40&v=4",
      },
    ],
  },
  {
    rank: 7,
    username: "medusajs",
    repositoryName: "medusa",
    url: "https://github.com/medusajs/medusa",
    description: "The open-source Shopify alternative⚡️",
    language: "JavaScript",
    languageColor: "#f1e05a",
    totalStars: 1964,
    forks: 153,
    starsSince: 57,
    since: "daily",
    builtBy: [
      {
        username: "srindom",
        url: "https://github.com/srindom",
        avatar: "https://avatars.githubusercontent.com/u/7554214?s=40&v=4",
      },
      {
        username: "olivermrbl",
        url: "https://github.com/olivermrbl",
        avatar: "https://avatars.githubusercontent.com/u/59018053?s=40&v=4",
      },
      {
        username: "sebastiannicolajsen",
        url: "https://github.com/sebastiannicolajsen",
        avatar: "https://avatars.githubusercontent.com/u/80953876?s=40&v=4",
      },
      {
        username: "pKorsholm",
        url: "https://github.com/pKorsholm",
        avatar: "https://avatars.githubusercontent.com/u/88927411?s=40&v=4",
      },
      {
        username: "zakariaelas",
        url: "https://github.com/zakariaelas",
        avatar: "https://avatars.githubusercontent.com/u/33696020?s=40&v=4",
      },
    ],
  },
  {
    rank: 8,
    username: "bryandlee",
    repositoryName: "animegan2-pytorch",
    url: "https://github.com/bryandlee/animegan2-pytorch",
    description: "PyTorch implementation of AnimeGANv2",
    language: "Jupyter Notebook",
    languageColor: "#DA5B0B",
    totalStars: 1629,
    forks: 181,
    starsSince: 128,
    since: "daily",
    builtBy: [
      {
        username: "bryandlee",
        url: "https://github.com/bryandlee",
        avatar: "https://avatars.githubusercontent.com/u/26464535?s=40&v=4",
      },
      {
        username: "xhlulu",
        url: "https://github.com/xhlulu",
        avatar: "https://avatars.githubusercontent.com/u/21180505?s=40&v=4",
      },
      {
        username: "AK391",
        url: "https://github.com/AK391",
        avatar: "https://avatars.githubusercontent.com/u/81195143?s=40&v=4",
      },
      {
        username: "Sxela",
        url: "https://github.com/Sxela",
        avatar: "https://avatars.githubusercontent.com/u/11751592?s=40&v=4",
      },
    ],
  },
  {
    rank: 9,
    username: "yt-dlp",
    repositoryName: "yt-dlp",
    url: "https://github.com/yt-dlp/yt-dlp",
    description: "A youtube-dl fork with additional features and fixes",
    language: "Python",
    languageColor: "#3572A5",
    totalStars: 10865,
    forks: 710,
    starsSince: 67,
    since: "daily",
    builtBy: [
      {
        username: "dstftw",
        url: "https://github.com/dstftw",
        avatar: "https://avatars.githubusercontent.com/u/1908898?s=40&v=4",
      },
      {
        username: "phihag",
        url: "https://github.com/phihag",
        avatar: "https://avatars.githubusercontent.com/u/779568?s=40&v=4",
      },
      {
        username: "remitamine",
        url: "https://github.com/remitamine",
        avatar: "https://avatars.githubusercontent.com/u/10879694?s=40&v=4",
      },
      {
        username: "jaimeMF",
        url: "https://github.com/jaimeMF",
        avatar: "https://avatars.githubusercontent.com/u/1239727?s=40&v=4",
      },
      {
        username: "yan12125",
        url: "https://github.com/yan12125",
        avatar: "https://avatars.githubusercontent.com/u/1937689?s=40&v=4",
      },
    ],
  },
  {
    rank: 10,
    username: "jwasham",
    repositoryName: "coding-interview-university",
    url: "https://github.com/jwasham/coding-interview-university",
    description:
      "A complete computer science study plan to become a software engineer.",
    language: null,
    languageColor: null,
    totalStars: 197907,
    forks: 53251,
    starsSince: 225,
    since: "daily",
    builtBy: [
      {
        username: "jwasham",
        url: "https://github.com/jwasham",
        avatar: "https://avatars.githubusercontent.com/u/3771963?s=40&v=4",
      },
      {
        username: "avizmarlon",
        url: "https://github.com/avizmarlon",
        avatar: "https://avatars.githubusercontent.com/u/24354489?s=40&v=4",
      },
      {
        username: "esaucedof",
        url: "https://github.com/esaucedof",
        avatar: "https://avatars.githubusercontent.com/u/13459501?s=40&v=4",
      },
      {
        username: "aleen42",
        url: "https://github.com/aleen42",
        avatar: "https://avatars.githubusercontent.com/u/9573300?s=40&v=4",
      },
      {
        username: "Ilyushin",
        url: "https://github.com/Ilyushin",
        avatar: "https://avatars.githubusercontent.com/u/4519586?s=40&v=4",
      },
    ],
  },
  {
    rank: 11,
    username: "TachibanaYoshino",
    repositoryName: "AnimeGANv2",
    url: "https://github.com/TachibanaYoshino/AnimeGANv2",
    description:
      "[Open Source]. The improved version of AnimeGAN. Landscape photos/videos to anime",
    language: "Python",
    languageColor: "#3572A5",
    totalStars: 1728,
    forks: 210,
    starsSince: 134,
    since: "daily",
    builtBy: [
      {
        username: "jwasham",
        url: "https://github.com/jwasham",
        avatar: "https://avatars.githubusercontent.com/u/3771963?s=40&v=4",
      },
      {
        username: "avizmarlon",
        url: "https://github.com/avizmarlon",
        avatar: "https://avatars.githubusercontent.com/u/24354489?s=40&v=4",
      },
      {
        username: "esaucedof",
        url: "https://github.com/esaucedof",
        avatar: "https://avatars.githubusercontent.com/u/13459501?s=40&v=4",
      },
      {
        username: "aleen42",
        url: "https://github.com/aleen42",
        avatar: "https://avatars.githubusercontent.com/u/9573300?s=40&v=4",
      },
      {
        username: "Ilyushin",
        url: "https://github.com/Ilyushin",
        avatar: "https://avatars.githubusercontent.com/u/4519586?s=40&v=4",
      },
    ],
  },
  {
    rank: 12,
    username: "Python-World",
    repositoryName: "python-mini-projects",
    url: "https://github.com/Python-World/python-mini-projects",
    description:
      "A collection of simple python mini projects to enhance your python skills",
    language: "Python",
    languageColor: "#3572A5",
    totalStars: 8043,
    forks: 2092,
    starsSince: 80,
    since: "daily",
    builtBy: [
      {
        username: "AdityaJ7",
        url: "https://github.com/AdityaJ7",
        avatar: "https://avatars.githubusercontent.com/u/42397096?s=40&v=4",
      },
      {
        username: "chavarera",
        url: "https://github.com/chavarera",
        avatar: "https://avatars.githubusercontent.com/u/33047641?s=40&v=4",
      },
      {
        username: "tripleee",
        url: "https://github.com/tripleee",
        avatar: "https://avatars.githubusercontent.com/u/2160915?s=40&v=4",
      },
      {
        username: "Mitesh2499",
        url: "https://github.com/Mitesh2499",
        avatar: "https://avatars.githubusercontent.com/u/46081187?s=40&v=4",
      },
      {
        username: "ShivSt",
        url: "https://github.com/ShivSt",
        avatar: "https://avatars.githubusercontent.com/u/61498906?s=40&v=4",
      },
    ],
  },
  {
    rank: 13,
    username: "LSPosed",
    repositoryName: "MagiskOnWSA",
    url: "https://github.com/LSPosed/MagiskOnWSA",
    description:
      "Integrate Magisk root and Google Apps (OpenGApps) into WSA (Windows Subsystem for Android)",
    language: null,
    languageColor: null,
    totalStars: 1717,
    forks: 12941,
    starsSince: 89,
    since: "daily",
    builtBy: [
      {
        username: "yujincheng08",
        url: "https://github.com/yujincheng08",
        avatar: "https://avatars.githubusercontent.com/u/5022927?s=40&v=4",
      },
      {
        username: "Howard20181",
        url: "https://github.com/Howard20181",
        avatar: "https://avatars.githubusercontent.com/u/40033067?s=40&v=4",
      },
      {
        username: "pazhanir",
        url: "https://github.com/pazhanir",
        avatar: "https://avatars.githubusercontent.com/u/22587698?s=40&v=4",
      },
      {
        username: "zhongfly",
        url: "https://github.com/zhongfly",
        avatar: "https://avatars.githubusercontent.com/u/11155705?s=40&v=4",
      },
      {
        username: "SekiBetu",
        url: "https://github.com/SekiBetu",
        avatar: "https://avatars.githubusercontent.com/u/38283893?s=40&v=4",
      },
    ],
  },
  {
    rank: 14,
    username: "ava-labs",
    repositoryName: "avalanchego",
    url: "https://github.com/ava-labs/avalanchego",
    description: "Go implementation of an Avalanche node.",
    language: "Go",
    languageColor: "#00ADD8",
    totalStars: 1038,
    forks: 218,
    starsSince: 52,
    since: "daily",
    builtBy: [
      {
        username: "StephenButtolph",
        url: "https://github.com/StephenButtolph",
        avatar: "https://avatars.githubusercontent.com/u/22109487?s=40&v=4",
      },
      {
        username: "danlaine",
        url: "https://github.com/danlaine",
        avatar: "https://avatars.githubusercontent.com/u/16107447?s=40&v=4",
      },
      {
        username: "aaronbuchwald",
        url: "https://github.com/aaronbuchwald",
        avatar: "https://avatars.githubusercontent.com/u/24684335?s=40&v=4",
      },
      {
        username: "manthanhd",
        url: "https://github.com/manthanhd",
        avatar: "https://avatars.githubusercontent.com/u/1021727?s=40&v=4",
      },
      {
        username: "abi87",
        url: "https://github.com/abi87",
        avatar: "https://avatars.githubusercontent.com/u/17881489?s=40&v=4",
      },
    ],
  },
  {
    rank: 15,
    username: "jackfrued",
    repositoryName: "Python-100-Days",
    url: "https://github.com/jackfrued/Python-100-Days",
    description: "Python - 100天从新手到大师",
    language: "Python",
    languageColor: "#3572A5",
    totalStars: 112102,
    forks: 43730,
    starsSince: 136,
    since: "daily",
    builtBy: [
      {
        username: "jackfrued",
        url: "https://github.com/jackfrued",
        avatar: "https://avatars.githubusercontent.com/u/7474657?s=40&v=4",
      },
      {
        username: "softpo",
        url: "https://github.com/softpo",
        avatar: "https://avatars.githubusercontent.com/u/13017944?s=40&v=4",
      },
      {
        username: "geekya215",
        url: "https://github.com/geekya215",
        avatar: "https://avatars.githubusercontent.com/u/10865729?s=40&v=4",
      },
      {
        username: "JalanJiang",
        url: "https://github.com/JalanJiang",
        avatar: "https://avatars.githubusercontent.com/u/7787716?s=40&v=4",
      },
      {
        username: "jankeromnes",
        url: "https://github.com/jankeromnes",
        avatar: "https://avatars.githubusercontent.com/u/599268?s=40&v=4",
      },
    ],
  },
  {
    rank: 16,
    username: "freqtrade",
    repositoryName: "freqtrade",
    url: "https://github.com/freqtrade/freqtrade",
    description: "Free, open source crypto trading bot",
    language: "Python",
    languageColor: "#3572A5",
    totalStars: 13379,
    forks: 2974,
    starsSince: 21,
    since: "daily",
    builtBy: [
      {
        username: "xmatthias",
        url: "https://github.com/xmatthias",
        avatar: "https://avatars.githubusercontent.com/u/5024695?s=40&v=4",
      },
      {
        username: "hroff-1902",
        url: "https://github.com/hroff-1902",
        avatar: "https://avatars.githubusercontent.com/u/47309513?s=40&v=4",
      },
      {
        username: "mishaker",
        url: "https://github.com/mishaker",
        avatar: "https://avatars.githubusercontent.com/u/939309?s=40&v=4",
      },
      {
        username: "pyup-bot",
        url: "https://github.com/pyup-bot",
        avatar: "https://avatars.githubusercontent.com/u/16239342?s=40&v=4",
      },
      {
        username: "vertti",
        url: "https://github.com/vertti",
        avatar: "https://avatars.githubusercontent.com/u/557751?s=40&v=4",
      },
    ],
  },
  {
    rank: 17,
    username: "Pierian-Data",
    repositoryName: "Complete-Python-3-Bootcamp",
    url: "https://github.com/Pierian-Data/Complete-Python-3-Bootcamp",
    description: "Course Files for Complete Python 3 Bootcamp Course on Udemy",
    language: "Jupyter Notebook",
    languageColor: "#DA5B0B",
    totalStars: 17944,
    forks: 62493,
    starsSince: 27,
    since: "daily",
    builtBy: [
      {
        username: "TiVentures",
        url: "https://github.com/TiVentures",
        avatar: "https://avatars.githubusercontent.com/u/28677216?s=40&v=4",
      },
      {
        username: "Pierian-Data",
        url: "https://github.com/Pierian-Data",
        avatar: "https://avatars.githubusercontent.com/u/16237870?s=40&v=4",
      },
      {
        username: "Knight-coder",
        url: "https://github.com/Knight-coder",
        avatar: "https://avatars.githubusercontent.com/u/72149616?s=40&v=4",
      },
      {
        username: "sprutner",
        url: "https://github.com/sprutner",
        avatar: "https://avatars.githubusercontent.com/u/3011275?s=40&v=4",
      },
    ],
  },
  {
    rank: 18,
    username: "donnemartin",
    repositoryName: "system-design-primer",
    url: "https://github.com/donnemartin/system-design-primer",
    description:
      "Learn how to design large-scale systems. Prep for the system design interview. Includes Anki flashcards.",
    language: "Python",
    languageColor: "#3572A5",
    totalStars: 150828,
    forks: 27856,
    starsSince: 104,
    since: "daily",
    builtBy: [
      {
        username: "donnemartin",
        url: "https://github.com/donnemartin",
        avatar: "https://avatars.githubusercontent.com/u/5458997?s=40&v=4",
      },
      {
        username: "satob",
        url: "https://github.com/satob",
        avatar: "https://avatars.githubusercontent.com/u/171818?s=40&v=4",
      },
      {
        username: "fluency03",
        url: "https://github.com/fluency03",
        avatar: "https://avatars.githubusercontent.com/u/7440735?s=40&v=4",
      },
      {
        username: "sqrthree",
        url: "https://github.com/sqrthree",
        avatar: "https://avatars.githubusercontent.com/u/8622362?s=40&v=4",
      },
      {
        username: "antongulikov",
        url: "https://github.com/antongulikov",
        avatar: "https://avatars.githubusercontent.com/u/6084440?s=40&v=4",
      },
    ],
  },
  {
    rank: 19,
    username: "whittlem",
    repositoryName: "pycryptobot",
    url: "https://github.com/whittlem/pycryptobot",
    description: "Python Crypto Bot",
    language: "Python",
    languageColor: "#3572A5",
    totalStars: 1116,
    forks: 408,
    starsSince: 30,
    since: "daily",
    builtBy: [
      {
        username: "whittlem",
        url: "https://github.com/whittlem",
        avatar: "https://avatars.githubusercontent.com/u/19817919?s=40&v=4",
      },
      {
        username: "markhollingworth-worthit",
        url: "https://github.com/markhollingworth-worthit",
        avatar: "https://avatars.githubusercontent.com/u/61147577?s=40&v=4",
      },
      {
        username: "edrickrenan",
        url: "https://github.com/edrickrenan",
        avatar: "https://avatars.githubusercontent.com/u/16997986?s=40&v=4",
      },
      {
        username: "rcarmo",
        url: "https://github.com/rcarmo",
        avatar: "https://avatars.githubusercontent.com/u/392683?s=40&v=4",
      },
      {
        username: "chriskoepf",
        url: "https://github.com/chriskoepf",
        avatar: "https://avatars.githubusercontent.com/u/12001829?s=40&v=4",
      },
    ],
  },
  {
    rank: 20,
    username: "itdevbooks",
    repositoryName: "pdf",
    url: "https://github.com/itdevbooks/pdf",
    description:
      "编程电子书，电子书，编程书籍，包括C，C#，Docker，Elasticsearch，Git，Hadoop，HeadFirst，Java，Javascript，jvm，Kafka，Linux，Maven，MongoDB，MyBatis，MySQL，Netty，Nginx，Python，RabbitMQ，Redis，Scala，Solr，Spark，Spring，SpringBoot，SpringCloud，TCPIP，Tomcat，Zookeeper，人工智能，大数据类，并发编程，数据库类，数据挖掘，新面试题，架构设计，算法系列，计算机类，设计模式，软件测试，重构优化，等更多分类",
    language: null,
    languageColor: null,
    totalStars: 10989,
    forks: 3546,
    starsSince: 67,
    since: "daily",
    builtBy: [
      {
        username: "itdevbooks",
        url: "https://github.com/itdevbooks",
        avatar: "https://avatars.githubusercontent.com/u/77837197?s=40&v=4",
      },
    ],
  },
  {
    rank: 21,
    username: "cloudflare",
    repositoryName: "production-saas",
    url: "https://github.com/cloudflare/production-saas",
    description:
      "(WIP) Example SaaS application built in public on the Cloudflare stack!",
    language: "TypeScript",
    languageColor: "#2b7489",
    totalStars: 683,
    forks: 18,
    starsSince: 105,
    since: "daily",
    builtBy: [
      {
        username: "lukeed",
        url: "https://github.com/lukeed",
        avatar: "https://avatars.githubusercontent.com/u/5855893?s=40&v=4",
      },
    ],
  },
  {
    rank: 22,
    username: "davidrmiller",
    repositoryName: "biosim4",
    url: "https://github.com/davidrmiller/biosim4",
    description: "Biological evolution simulator",
    language: "C++",
    languageColor: "#f34b7d",
    totalStars: 889,
    forks: 122,
    starsSince: 136,
    since: "daily",
    builtBy: [
      {
        username: "davidrmiller",
        url: "https://github.com/davidrmiller",
        avatar: "https://avatars.githubusercontent.com/u/9440676?s=40&v=4",
      },
      {
        username: "MJoergen",
        url: "https://github.com/MJoergen",
        avatar: "https://avatars.githubusercontent.com/u/1299486?s=40&v=4",
      },
    ],
  },
  {
    rank: 23,
    username: "yaronzz",
    repositoryName: "Tidal-Media-Downloader",
    url: "https://github.com/yaronzz/Tidal-Media-Downloader",
    description: "Download 'TIDAL' Music On Windows/Linux/MacOs (PYTHON/C#)",
    language: "Python",
    languageColor: "#3572A5",
    totalStars: 1425,
    forks: 280,
    starsSince: 12,
    since: "daily",
    builtBy: [
      {
        username: "yaronzz",
        url: "https://github.com/yaronzz",
        avatar: "https://avatars.githubusercontent.com/u/15530958?s=40&v=4",
      },
      {
        username: "moisespr123",
        url: "https://github.com/moisespr123",
        avatar: "https://avatars.githubusercontent.com/u/16326634?s=40&v=4",
      },
      {
        username: "Frikilinux",
        url: "https://github.com/Frikilinux",
        avatar: "https://avatars.githubusercontent.com/u/314234?s=40&v=4",
      },
      {
        username: "harryt04",
        url: "https://github.com/harryt04",
        avatar: "https://avatars.githubusercontent.com/u/22422276?s=40&v=4",
      },
      {
        username: "SPAstef",
        url: "https://github.com/SPAstef",
        avatar: "https://avatars.githubusercontent.com/u/9153046?s=40&v=4",
      },
    ],
  },
  {
    rank: 24,
    username: "TBDev-54566975",
    repositoryName: "white-paper",
    url: "https://github.com/TBDev-54566975/white-paper",
    description: null,
    language: "TeX",
    languageColor: "#3D6117",
    totalStars: 230,
    forks: 13,
    starsSince: 31,
    since: "daily",
    builtBy: [
      {
        username: "csuwildcat",
        url: "https://github.com/csuwildcat",
        avatar: "https://avatars.githubusercontent.com/u/131786?s=40&v=4",
      },
      {
        username: "mistermoe",
        url: "https://github.com/mistermoe",
        avatar: "https://avatars.githubusercontent.com/u/4887440?s=40&v=4",
      },
    ],
  },
  {
    rank: 25,
    username: "coolsnowwolf",
    repositoryName: "lede",
    url: "https://github.com/coolsnowwolf/lede",
    description: "Lean's OpenWrt source",
    language: "C",
    languageColor: "#555555",
    totalStars: 18688,
    forks: 15584,
    starsSince: 35,
    since: "daily",
    builtBy: [
      {
        username: "coolsnowwolf",
        url: "https://github.com/coolsnowwolf",
        avatar: "https://avatars.githubusercontent.com/u/31687149?s=40&v=4",
      },
      {
        username: "Beginner-Go",
        url: "https://github.com/Beginner-Go",
        avatar: "https://avatars.githubusercontent.com/u/70857188?s=40&v=4",
      },
      {
        username: "AmadeusGhost",
        url: "https://github.com/AmadeusGhost",
        avatar: "https://avatars.githubusercontent.com/u/42570690?s=40&v=4",
      },
      {
        username: "1715173329",
        url: "https://github.com/1715173329",
        avatar: "https://avatars.githubusercontent.com/u/22235437?s=40&v=4",
      },
      {
        username: "Mattraks",
        url: "https://github.com/Mattraks",
        avatar: "https://avatars.githubusercontent.com/u/16359027?s=40&v=4",
      },
    ],
  },
];

export default repositories;
